server :
    port : 8083

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}

logging:
    file:
        name: logs/application.log       # File path for logs
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    level:
        root: INFO                       # Default logging level
        com.cosmacare: DEBUG              # package-specific logging

spring:
    application:
        name: reward-service

    data:
        mongodb:
            host: localhost
            port: 27018
            database: rewarddb
            username: rewardadmin
            password: rewardadmin123
            authentication-database: admin   # required for root user

# Prometheus
management:
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /actuator
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true
        enable:
            all=true: