server :
    port : 8083

eureka :
    client :
        service-url :
            defaultZone : http://localhost:8761/eureka/

spring:
    application:
        name: reward-service

    data:
        mongodb:
            host: localhost
            port: 27018
            database: rewarddb
            username: rewardadmin
            password: rewardadmin123
            authentication-database: admin   # required for root user