server:
    port: 8084

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}

logging:
    file:
        name: logs/application.log       # File path for logs
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    level:
        root: INFO                       # Default logging level
        com.cosmacare: DEBUG              # package-specific logging

spring:
    application:
        name: notification-service

    mail:
        host: smtp.gmail.com
        port: 587
        username: jatharyv@gmail.com
        password: imny fywp qxvs brpv
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    data:
        mongodb:
            host: localhost
            port: 27019
            database: notification_db
            username: notification_admin
            password: notification_admin123
            authentication-database: admin

    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            group-id: notification-group
            auto-offset-reset: earliest
            properties:
                spring.json.trusted.packages: "com.cosmacare.notification_service.dto"
                spring.json.use.type.headers: false

# Prometheus
management:
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /actuator
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true
        enable:
            all=true:

