eureka :
  client :
    service-url :
      defaultZone : http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**

        - id: repair-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/repair/**

        - id: reward-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/rewards/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**

        - id: security-service
          uri: http://localhost:9095
          predicates:
            - Path=/auth/**


jwt:
  secret: "afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf"