server :
    port : 8761

eureka:
    client:
        register-with-eureka: false  # Eureka server itself does not register
        fetch-registry: false
    server:
        enable-self-preservation: false

spring:
    application:
        name: eureka-server
