server:
    port: 8082

eureka :
    client :
        service-url :
            defaultZone : http://localhost:8761/eureka/

logging :
    level :
        root : INFO
spring:
    application:
        name: repair-service

    data:
        mongodb:
            host: localhost
            port: 27017
            database: repair_db
            username: repair_admin
            password: repair_admin123
            authentication-database: admin   # required for root user

    kafka:
        bootstrap-servers: cosmacare-kafka-server:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
#            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
    secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf