server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}

logging:
    file:
        name: logs/application.log       # File path for logs
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    level:
        root: INFO                       # Default logging level
        com.cosmacare: DEBUG              # package-specific logging

spring:
    application:
        name: repair-service

    data:
        mongodb:
            host: localhost
            port: 27017
            database: repair_db
            username: repair_admin
            password: repair_admin123
            authentication-database: admin   # required for root user

    kafka:
        bootstrap-servers: cosmacare-kafka-server:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
#            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
    secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf

# Prometheus
management:
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /actuator
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true
        enable:
            all=true: